--- 
  - name: start dnsmasq 
    systemd: 
      name: dnsmasq 
      state: started 


  - name: stop dnsmasq 
    systemd: 
      name: dnsmasq 
      state: stopped 


  - name: reload dnsmasq 
    systemd: 
      name: dnsmasq 
      state: reloaded 

  - name: enable dnsmasq 
    systemd: 
      name: dnsmasq 
      enabled: true 

  - name: start n enable 
    systemd: 
      name: dnsmasq 
      state: started 
      enabled: true 

  - name: stop n disable 
    systemd: 
      name: dnsmasq 
      state: stopped 
      enabled: false 
