--- 


  # // firewall handlers 
  - name: reload firewall 
    systemd: 
      name: firewalld 
      state: reloaded 

  - name: restart firewall 
    systemd: 
      name: firewalld 
      state: restarted 

  - name: start firewall 
    systemd: 
      name: firewalld 
      state: started 
      
  - name: stop firewall 
    systemd: 
      name: firewalld 
      state: stopped 
      
    


  # // openssh server handlers.
  - name: reload sshd 
    systemd: 
      name: sshd
      state: reloaded 


  - name: restart sshd 
    systemd: 
      name: 'sshd' 
      state: restarted 

  - name: enable sshd 
    systemd: 
      name: 'sshd' 
      state: started 
      enabled: 'true' 
      