--- 

- name: Allowing incoming web/ssh connections... 
  ansible.posix.firewalld:
    service: "{{ item }}" 
    zone: "{{ default_zone }}" 
    state: enabled
    permanent: true
    immediate: true
    offline: true

  loop: "{{ services_in }}" 


- name: Allowing incoming connections on MISC ports... 
  ansible.posix.firewalld: 
    port: "{{ item }}/tcp" 
    zone: "{{ default_zone }}"
    state: enabled 
    permanent: true 
    immediate: true 
    offline: true 

  loop: "{{ ports_in }}" 
  # // notifying handler to reload 
  notify: "reload firewall" 







  
