--- 

- name: Set firewalld default zone to public
  ansible.posix.firewalld:
    zone: "{{ default_zone }}" 
    state: enabled
    permanent: true
    immediate: true


- name: Allow incoming https 
  ansible.posix.firewalld:
    service: "{{ item }}" 
    state: enabled
    permanent: true
    immediate: true
    offline: true

  loop: "{{ services_in }}" 


- name: Allowing incoming connections on MISC ports... 
  ansible.posix.firewalld: 
    port: "{{ item }}/tcp" 
    state: enabled 
    permanent: true 
    immediate: true 
    offline: true 

  loop: "{{ ports_in }}" 

- name: Reloading firewall... 
  systemd: 
    name: "firewalld" 
    state: reloaded 
    daemon_reload: True 










  
