--- 

  - name: Deploying dnsmasq configurations... 
    template: 
      src: "{{ item.src }}"
      dest: "{{ item.dest }}" 
      owner: 'root'
      group: 'root' 
      mode: '0644'

    loop: 
      - { src: 'dnsmasq.conf.j2', dest: '/etc/dnsmasq.conf' }

  - name: Disabling `systemd-resolved` ... 
    systemd: 
      name: systemd-resolved
      state: stopped 
      enabled: false 


  - name: Setting up resolv.conf... 
    template: 
      src: resolv.conf.j2 
      dest: /etc/resolv.conf
      owner: 'root'
      group: 'root'
      mode: '0644'  
    # // notify handler to perform `systemctl enable --now dnsmasq`. 
    notify: "start n enable"