--- 

  - name: Installing dependencies... 
    dnf: 
      name: "{{ dnsmasq_packages }}" 
      state: latest
    register: dnsmasq_install  
    retries: 3 
    delay: 2 
    until: dnsmasq_install is successful


  - name: Deploying config files. 
    template: 
      src: "{{ item.src }}"
      dest: "{{ item.dest }}" 
      owner: 'root'
      group: 'root' 
      mode: '0644'

    loop: 
      - { src: 'dnsmasq.conf.j2', dest: '/etc/dnsmasq.conf' }

  - name: Switching from systemd-resolved to NetworkManager 
    systemd: 
      name: systemd-resolved
      state: stopped 
      enabled: false 


  - name: Setting up resolv.conf 
    template: 
      src: resolv.conf.j2 
      dest: /etc/resolv.conf
      owner: 'root'
      group: 'root'
      mode: '0644'


  - name: Starting dnsmasq...
    systemd:
        name: dnsmasq
        state: started
        enabled: true
