server_hostname: "core2.local" 
node_ip: "192.168.100.144" 





# // firewalld variables 
services_in: 
  - https 
  - http 
  - ssh  
  
ports_in: 
  - 9090 
  - 3301   
  - 2222 
  - 22 

ssh_port: "2222" 


default_zone: "public" 
default_policy: "DROP" 

